version: "2"
services:
  app:
    build: .
    ports:
    - "8088:8088"
    environment:
    - EVENTSTORE=http://eventstore:2113
    links:
    - eventstore
  eventstore:
    image: eventstore/eventstore
    ports:
    - "2113:2113"
    - "1113:1113"